export const reportData = {
    reportGroup: [
        {
            MilkId: '01000010',
            Analysed: 'Yes',
            Protein: '4.4',
            Fat: '5.4',
            Carbs: '8.4',
            Energy: '84',
        },
        {
            MilkId: '01000020',
            Analysed: 'No',
            Protein: '0',
            Fat: '0',
            Carbs: '0',
            Energy: '0',
        },
        {
            MilkId: '01000030',
            Analysed: 'Yes',
            Protein: '4.3',
            Fat: '5.3',
            Carbs: '7.3',
            Energy: '73',
        },
        {
            MilkId: '01000040',
            Analysed: 'Yes',
            Protein: '3.9',
            Fat: '5.9',
            Carbs: '8.9',
            Energy: '89',
        },
        {
            MilkId: '01000050',
            Analysed: 'No',
            Protein: '0',
            Fat: '0',
            Carbs: '0',
            Energy: '0',
        },
        {
            MilkId: '01000060',
            Analysed: 'Yes',
            Protein: '1.7',
            Fat: '5.7',
            Carbs: '8.7',
            Energy: '87',
        },
        {
            MilkId: '01000070',
            Analysed: 'No',
            Protein: '0',
            Fat: '0',
            Carbs: '0',
            Energy: '0',
        },
        {
            MilkId: '01000080',
            Analysed: 'No',
            Protein: '0',
            Fat: '0',
            Carbs: '0',
            Energy: '0',
        },
        {
            MilkId: '01000010',
            Analysed: 'Yes',
            Protein: '1.4',
            Fat: '2.2',
            Carbs: '7.2',
            Energy: '72',
        },
    ],
};
